#ifndef ANGELSCRIPT_SCRIPTAPI_SQL_MYSQL_ASMYSQL_H
#define ANGELSCRIPT_SCRIPTAPI_SQL_MYSQL_ASMYSQL_H

class asIScriptEngine;

void RegisterScriptMySQL( asIScriptEngine& engine );

#endif //ANGELSCRIPT_SCRIPTAPI_SQL_MYSQL_ASMYSQL_H